// Runs after `next build` (static export). Generates, from the canonical content modules:
//   out/.htaccess  — HTTPS/host canonicalisation, legacy 301s, image 301s, trailing slash, 404, headers, caching
//   out/llms.txt   — concise machine-readable site summary
//   out/redirects.json — machine-readable redirect map (for other hosts / auditing)
// Node ≥22.18 strips TypeScript types natively, so content/*.ts is imported directly.
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { join } from "node:path";
import { redirects } from "../content/redirects.ts";
import { company, site, sites } from "../content/company.ts";
import { articles } from "../content/insights.ts";
import { applications } from "../content/applications.ts";
import { colourGrades, origins, labReports, meshCapability, packing } from "../content/talc.ts";
import { seo } from "../content/seo.ts";

const OUT = "out";
if (!existsSync(OUT)) throw new Error("out/ not found — run next build first");

const host = new URL(site.url).host; // paktalc.com
const esc = (s) => s.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
const strip = (p) => p.replace(/^\//, "");

// ---------- image redirects from the prepared CSV ----------
const csv = readFileSync("paktalc-image-redirects.csv", "utf8").trim().split(/\r?\n/).slice(1);
const imageRedirects = csv
  .map((line) => line.split(","))
  .filter((c) => c[0] && c[1])
  .map(([from, to, asset, status]) => ({ from, to, asset, status: status?.trim() || "301" }));

// Validate: every image target must exist in out/
const missing = imageRedirects.filter((r) => !existsSync(join(OUT, r.to)));
if (missing.length) {
  console.warn(`! ${missing.length} image redirect targets missing in out/:`, missing.slice(0, 5).map((m) => m.to));
}

// Validate: page redirect targets are real routes, and never another redirect source (no chains)
const sources = new Set(redirects.map((r) => r.from));
for (const r of redirects) {
  if (sources.has(r.to)) throw new Error(`Redirect chain: ${r.from} → ${r.to} is itself redirected`);
  const target = join(OUT, r.to, "index.html");
  if (!existsSync(target)) throw new Error(`Redirect target does not exist: ${r.to}`);
}

// Exact rules first, then prefix rules (longest first) so specific mappings win.
const exact = redirects.filter((r) => !r.prefix);
const prefix = redirects.filter((r) => r.prefix).sort((a, b) => b.from.length - a.from.length);

const lines = [];
const L = (s = "") => lines.push(s);

L("# Generated by scripts/postbuild.mjs — do not edit by hand. Source: content/redirects.ts, paktalc-image-redirects.csv");
L("Options -Indexes -MultiViews");
L("DirectoryIndex index.html index.php");
L("ErrorDocument 404 /404.html");
L("AddDefaultCharset utf-8");
L();
L("<IfModule mod_mime.c>");
L("  AddType image/avif .avif");
L("  AddType image/webp .webp");
L("  AddType text/plain .txt");
L("  AddType application/manifest+json .webmanifest");
L("</IfModule>");
L();
L("<IfModule mod_rewrite.c>");
L("RewriteEngine On");
L("RewriteBase /");
L();
// Every redirect target is absolute (https + canonical host), and legacy rules run BEFORE host canonicalisation,
// so any old URL (http://, www., missing slash…) reaches its final page in exactly one hop.
const abs = (p) => `https://${host}${p}`;
L("# --- 1. Legacy WordPress pages (one-to-one, see REDIRECT-PLAN.md) ---");
for (const r of exact) L(`RewriteRule ^${esc(strip(r.from)).replace(/\/$/, "")}/?$ ${abs(r.to)} [R=301,L]`);
for (const r of prefix) L(`RewriteRule ^${esc(strip(r.from))}.*$ ${abs(r.to)} [R=301,L]`);
L("# WordPress query-string URLs (?p=, ?page_id=, ?s=) → home");
L("RewriteCond %{QUERY_STRING} (^|&)(p|page_id|s|cat|tag|author)=[^&]* [NC]");
L(`RewriteRule ^$ ${abs("/")}? [R=301,L]`);
L("RewriteRule ^wp-(admin|login\\.php|json|includes)(/.*)?$ - [R=410,L]");
L("RewriteRule ^xmlrpc\\.php$ - [R=410,L]");
L();
L(`# --- 2. Legacy WordPress image URLs (${imageRedirects.length} rules, preserves image SEO) ---`);
for (const r of imageRedirects) L(`RewriteRule ^${esc(strip(r.from))}$ ${abs(r.to)} [R=${r.status},L]`);
L();
L("# --- 3. Trailing slash for extension-less directory paths (absolute target → also fixes host in the same hop) ---");
L("RewriteCond %{HTTP_HOST} !^(localhost|127\\.0\\.0\\.1)(:\\d+)?$ [NC]");
L("RewriteCond %{REQUEST_FILENAME} !-f");
L("RewriteCond %{REQUEST_URI} !/$");
L("RewriteCond %{REQUEST_URI} !\\.[a-zA-Z0-9]{1,6}$");
L("RewriteCond %{REQUEST_FILENAME}/index.html -f");
L(`RewriteRule ^(.*)$ https://${host}/$1/ [R=301,L]`);
L();
L("# --- 4. Canonical host + HTTPS (skipped on localhost) ---");
L("RewriteCond %{HTTP_HOST} !^(localhost|127\\.0\\.0\\.1)(:\\d+)?$ [NC]");
L(`RewriteCond %{HTTPS} off [OR]`);
L(`RewriteCond %{HTTP_HOST} !^${esc(host)}$ [NC]`);
L(`RewriteRule ^(.*)$ https://${host}/$1 [R=301,L]`);
L("</IfModule>");
L();
L("# --- Security headers ---");
L("<IfModule mod_headers.c>");
L('  Header always set X-Content-Type-Options "nosniff"');
L('  Header always set Referrer-Policy "strict-origin-when-cross-origin"');
L('  Header always set X-Frame-Options "SAMEORIGIN"');
L('  Header always set Permissions-Policy "camera=(), microphone=(), geolocation=(), payment=(), usb=(), interest-cohort=()"');
L('  Header always set Cross-Origin-Opener-Policy "same-origin"');
L("  # HSTS: enable only once HTTPS is confirmed working on the production host.");
L('  Header always set Strict-Transport-Security "max-age=31536000; includeSubDomains" "expr=%{HTTPS} == \'on\'"');
L(
  "  # 'unsafe-inline' for scripts is required by Next.js static-export inline RSC payloads; Turnstile is allowed for the RFQ form.",
);
L(
  `  Header always set Content-Security-Policy "default-src 'self'; script-src 'self' 'unsafe-inline' https://challenges.cloudflare.com; style-src 'self' 'unsafe-inline'; img-src 'self' data:; font-src 'self'; connect-src 'self' https://challenges.cloudflare.com; frame-src https://challenges.cloudflare.com; frame-ancestors 'self'; base-uri 'self'; form-action 'self'; object-src 'none'; upgrade-insecure-requests"`,
);
L("  Header unset X-Powered-By");
L("  # Caching: hashed build assets are immutable; images long-lived; HTML revalidated.");
L('  <FilesMatch "\\.(avif|webp|png|jpg|jpeg|svg|ico|woff2)$">');
L('    Header set Cache-Control "public, max-age=2592000"');
L("  </FilesMatch>");
L('  <FilesMatch "\\.(html|xml|txt)$">');
L('    Header set Cache-Control "public, max-age=0, must-revalidate"');
L("  </FilesMatch>");
L("</IfModule>");
L('<IfModule mod_headers.c>');
L('  <If "%{REQUEST_URI} =~ m#^/_next/static/#">');
L('    Header set Cache-Control "public, max-age=31536000, immutable"');
L("  </If>");
L("</IfModule>");
L();
L("<IfModule mod_deflate.c>");
L("  AddOutputFilterByType DEFLATE text/html text/css application/javascript text/javascript application/json image/svg+xml text/plain application/xml text/xml");
L("</IfModule>");
L();
L("# Never serve dotfiles or source maps");
L('<FilesMatch "(^\\.|\\.map$)">');
L("  Require all denied");
L("</FilesMatch>");
L('<Files ".htaccess">');
L("  Require all denied");
L("</Files>");

writeFileSync(join(OUT, ".htaccess"), lines.join("\n") + "\n");
writeFileSync(
  join(OUT, "redirects.json"),
  JSON.stringify({ pages: redirects, images: imageRedirects.map(({ from, to }) => ({ from, to })) }, null, 2),
);

// ---------- llms.txt ----------
const u = (p) => `${site.url}${p}`;
const llms = `# ${site.name}

> ${company.shortDescription}

PakTalc is ${company.relationship} (${company.parent.url}). PakTalc covers talc only; SKZ Mining Company presents its other minerals on its own website.

## Products
- [Talc lumps](${u("/talc/lumps/")}): hand-sorted raw talc (soapstone), graded by colour (${colourGrades.map((g) => g.name.toLowerCase()).join(", ")}) and size, supplied un-ground in jumbo bags.
- [Talc powder](${u("/talc/powder/")}): talc ground on hammer and Raymond mill lines in Peshawar and classified to the buyer's fineness (company records rate the meshing plants for ${meshCapability.plantRange}; published sample reports: ${meshCapability.reportedSamples.join(", ")}). Packed in ${packing.formats.slice(0, 2).map((f) => f.name.toLowerCase()).join(" or ")}.
- [Talc overview](${u("/talc/")}): properties, terminology, colour grades and origins (${origins.afghan.label}: ${origins.afghan.sources.join(", ")}; ${origins.pakistani.label}: ${origins.pakistani.sources.join(", ")}).

## Operations
${sites.map((s) => `- ${s.name}, ${s.place}: ${s.role}`).join("\n")}
- [Mining operations](${u("/mining-operations/")}): geological survey, adits and underground chambers, selective extraction, hand sorting.
- [Processing](${u("/processing/")}): crushing, screening, grinding, classification, dust collection, testing, packing, dispatch.
- [Facilities](${u("/facilities/")})

## Quality
- [Quality control](${u("/quality-control/")}): checks at the mine, in the Peshawar yard and at SKZ Laboratory Peshawar (particle size by Bettersizer ST, whiteness by Konica colour reader, sieve residue, bulk density, LOI, SiO₂, MgO). ${labReports.length} sample reports are published; they are individual sample results, not guaranteed specifications. No certifications are claimed on this site.

## Applications
${applications.map((a) => `- [${a.name}](${u(`/applications/#${a.id}`)}): ${a.why}`).join("\n")}

## Company
- [About](${u("/about/")})
- [SKZ Mining affiliation](${u("/affiliation/")}): company structure and supply chain.
- [Sustainability](${u("/sustainability/")})

## Insights
${articles.map((a) => `- [${a.title}](${u(`/insights/${a.slug}/`)}): ${a.description}`).join("\n")}

## Contact
- Request a quotation: ${u("/contacts/")}
- Email: ${company.email}
- Phone: ${company.phone.display}
- Head office: ${company.headOffice.locality}, ${company.headOffice.country}
`;
writeFileSync(join(OUT, "llms.txt"), llms);

// Sanity: every indexable seo route must exist
for (const [path, v] of Object.entries(seo)) {
  if (!existsSync(join(OUT, path, "index.html"))) throw new Error(`Route in content/seo.ts not built: ${path}`);
  void v;
}

console.log(`postbuild: .htaccess (${exact.length + prefix.length} page rules, ${imageRedirects.length} image rules), redirects.json, llms.txt`);
